### ISSUE TITLE
Scrappers

### ISSUE THREAD

**Issue by bflanagin** [OpenSeedINC/CafeSync#1]
Scrappers are not functioning at the moment for some of the major social networks.

**Comment by bflanagin** [comment]
Disabling the non working scrappers will work as a band-aid. Getting developer id's and using the networks api's will be the best way to fix this issue.

**Comment by ryanleesipes** [comment]
Agreed ^.

**Comment by bflanagin** [comment]
Quick survey of the Scappers, Which work, Which dont

Twitter (Like a champ)
RSS (Yep got that too)
GoFundMe (80%)
KickStarter (could use a facelift but 100%)
Soundcloud (80%)



Facebook (images don't load, but data does)
Linkedin (beats me can't get it to respond)
Etsy(I was really proud of that one but doesn't load)
Youtube (50% loads backgrounds but not the preview.)
