### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by bflanagin** [OpenSeedINC/CafeSync#52]
Similar to chat but with a more "email" feel there will be no "room" created for them and it should be considered a fire and forget type interface.

This could also be used for system messages, or other heavier operations.

**Comment by ryanleesipes** [comment]
Will there be notifications?

**Comment by bflanagin** [comment]
Please refer to #47

**Comment by ryanleesipes** [comment]
Very cool.

**Comment by bflanagin** [comment]
I've narrowed the scope to only doing messaging instead of chat and messaging. It was redundant.
