### ISSUE TITLE
Text on Text when Editing Card

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/CafeSync#54]
Not sure what it's supposed to say, screenshot attached. This is whilst editing my own card.

![](https://i.imgur.com/S7UEUMD.jpg)

**Comment by bflanagin** [comment]
Well thats odd. Any chance I can get a version number from you. Should be somewhere in app info. And if possible whats the screen resolution on that there phone of yours.

**Comment by bflanagin** [comment]
I'm guessing by the rest of the image that the aspect on your phone is the issue. This is evident in how it handles the text next to Share Card. The newest version should fix this issue for you. I'll go through and check other possible overlaps and text sizing issues using thinner screens.
