### ISSUE TITLE
All Users Show Up In Passerby on iPhone

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/CafeSync#56]
All users show up in "Passerby" on iPhone. App doesn't show up in list of apps using location services in settings.

**Comment by bflanagin** [comment]
Looks like I the GPS code thinks no value is the same as being omni present. Easy to fix, also need to see whats up with the location services. Apples permissions aren't as straight forward as Androids. Rather I'm not as familiar with them.

**Comment by bflanagin** [comment]
Fixed the issue with the null values on iOS. Waiting on the store to update in order to get more real life data.

**Comment by bflanagin** [comment]
GPS finally functioning properly on iOS so not only does the entire list not show, it works as its supposed to.
