### ISSUE TITLE
Email address on iPhone Doesn't fit Container

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/CafeSync#57]
Email on iPhone doesn't fit container.

![](https://i.imgur.com/l26mqer.jpg)

**Comment by bflanagin** [comment]
The avatar area is really large too.
is this the 6 or the 8?

**Comment by bflanagin** [comment]
Messed around with this a bit. Set a maximum size for the avatar which in turn gives more room for the text, It looks to be fixed.
