### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by bflanagin** [OpenSeedINC/CafeSync#6]
Need to have a setup wizard for new users

**Comment by ryanleesipes** [comment]
I have shared some ideas for the first-time setup wizard here: https://github.com/orgs/OpenSeedINC/teams/cafesync-core-team/discussions/1

**Comment by bflanagin** [comment]
The Wizard.qml file is setup. Just need to created the scripts to put the info in the right places. Of course that requires a few other things to be created / changed. Wizards are great, but always a final touch given we don't know what we need until we need it.

**Comment by bflanagin** [comment]
First go is complete
