### ISSUE TITLE
Passerby staying around too long

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/CafeSync#62]
I got my Dad's card a couple of months ago, and it still hasn't cleared out of the passerby screen. Is this intended to work this way?

**Comment by bflanagin** [comment]
Maybe, do you have him saved in your contacts? the function that deletes the card is kind of dumb and might be failing if he is in both places.

**Comment by ryanleesipes** [comment]
Yes, he is saved in my contacts.

**Comment by bflanagin** [comment]
Okay that explains it.

**Comment by bflanagin** [comment]
Under more investigation I've found another issue. The temp list on the server is a little too sticky, in that the server should check the length of time the person has been at a location and 'ghost' them so that they don't get added back to the temp list.
