### ISSUE TITLE
Discussion: Passersby and Area

### ISSUE THREAD

**Issue by bflanagin** [OpenSeedINC/CafeSync#64]
In the original design there was a little area that gave you an idea of where you were (either region or passersby). Now the interface is far from what it once was, and I'm wondering if we need to change the name to "Collected" as that's a clearer definition of what its doing.

**Comment by ryanleesipes** [comment]
I do think this should be changed. "Collected" is pretty good, "Connect" would be fine to me. "Pocket" might be interesting.

While I'm typing this, collected is growing on me.

**Comment by bflanagin** [comment]
Well as we are the only two working on this. I'm going to make the change to Collected.

**Comment by bflanagin** [comment]
done
