### ISSUE TITLE
Can't finish writing message

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/CafeSync#65]
It wasn't this way in an earlier build, but now my messages I'm typing disappear from the text input field after only a few moments. They aren't invisible, but actually erased. I am not sure what is happening.

**Comment by bflanagin** [comment]
Verified, I think I can fix this when the Requests bug is squashed. It can't verify you are allowed to talk to the other party and thus its being hostile to you.

**Comment by bflanagin** [comment]
I've sent you a request to re-verify our connection. That should fix the issue.

**Comment by bflanagin** [comment]
Correction there were all sorts of things I know we're working before. I was able to finish messages and such.
