### ISSUE TITLE
Request: Add Status for Users

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/CafeSync#66]
In many ways CafeSync is a phone's contacts combined with a social network. I think it would be cool to have the ability to write a status like: "Enjoying Linux Fest Northwest! Stop by booth 203 to see me!" Perhaps the status only lasts a day, it would show up at the top of your card or below you when on the Collection screen.

**Comment by bflanagin** [comment]
I like that! Let me get whats working, working well and that will be added.

**Comment by bflanagin** [comment]
I added the placement for the status, if you like where i puts it. I'll add a way to add the status

**Comment by ryanleesipes** [comment]
I like it, what's the longest you can do?

**Comment by bflanagin** [comment]
244 characters, because why not?
