### ISSUE TITLE
How Do You Know Someone?

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/CafeSync#88]
When you make a connection, we should ask how you know someone so we can offer up ideas for stuff they should do together, how often they should meet (could have good, healthy advice articles available in the app), reminder notifications to go on a date with your girlfriend, and so on.

Relationship Types:

- Romance
- Family
- Friend
- Acquaintance
- Professional

**Comment by bflanagin** [comment]
I'm not sure about the articles part. Its a bit of a over reach IMO , and I think it would be more work for use to curate such a feature. The relational status thing is good though, and shouldn't be to hard to implement.
