### ISSUE TITLE
Ask to use Gravatar

### ISSUE THREAD

**Issue by ryanleesipes** [OpenSeedINC/CafeSync#9]
Since CafeSync asks at startup for an Email address, perhaps it should do a Gravatar check and ask if the user wants to use that? Same goes with Twitter and LinkedIn (once they are implemented). What do you think?

**Comment by bflanagin** [comment]
The email address at first doesn't necessarily have to be the one you use on the card. But of course to pull the url for the image the profile has to be saved. So there is room for improvement.  

I have plans to implement image capture / upload from inside the app, I could also see us using images pull from various networks once the user has set them up.

**Comment by ryanleesipes** [comment]
I put some more fleshed out ideas for first-time set up here: https://github.com/orgs/OpenSeedINC/teams/cafesync-core-team/discussions/1

**Comment by bflanagin** [comment]
CafeSync can now use a plethora of sources as well as the device's camera. User now has the ability to choose the best picture / service.
